name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths: [docs/**, .github/**]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.22.2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: pnpm
      - name: Build website
        working-directory: ./
        run: |
          pnpm install
          cd visual-editor
          pnpm run build
          cd ../docs 
          pnpm run build;
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/build

